import { Link } from 'react-router-dom';
import { cn } from '@/utils/cn';

/**
 * Brand lockup: the studio's round badge beside a typographic wordmark.
 *
 * Why both. The supplied logo is a complete badge — mark, script name and
 * tagline inside a circle. That reads beautifully at profile-picture size and
 * turns to mush in a 48px header, where the script would be about 10px tall.
 * Pairing the badge with set type keeps the brand recognisable AND legible,
 * which is the standard treatment for a round badge on the web.
 *
 * Sizes come from `public/assets/brand/`, generated by `npm run brand`.
 * The 2× source keeps it crisp on retina without shipping a large file.
 */
export const Logo = ({ tone = 'dark', className, onClick, showWordmark = true }) => (
  <Link
    to="/"
    onClick={onClick}
    aria-label="Studioz D — home"
    className={cn('group inline-flex shrink-0 items-center gap-2.5', className)}
    data-cursor="open"
  >
    <picture className="shrink-0">
      <source
        type="image/webp"
        srcSet="/assets/brand/studioz-d-logo-96.webp 1x, /assets/brand/studioz-d-logo-192.webp 2x"
      />
      <img
        src="/assets/brand/studioz-d-logo-96.png"
        srcSet="/assets/brand/studioz-d-logo-96.png 1x, /assets/brand/studioz-d-logo-192.png 2x"
        alt=""
        width={96}
        height={96}
        /**
         * Explicit box, so the header never reflows as the mark loads.
         *
         * Sized up from 36px: the badge is a white glossy sphere, which has
         * very little contrast against the ivory header. Below ~44px its
         * edge dissolves and it reads as a smudge rather than a logo. At
         * 40/48 the orange ring carries the shape. It still fits the 64/78px
         * header with room to spare.
         */
        className="h-10 w-10 object-contain sm:h-12 sm:w-12"
        decoding="async"
        // The header mark is above the fold on every page.
        fetchpriority="high"
      />
    </picture>

    {showWordmark && (
      <span className="flex min-w-0 flex-col leading-none">
        <span
          className={cn(
            'whitespace-nowrap font-display text-[clamp(0.98rem,0.9rem+0.42vw,1.2rem)] font-medium uppercase leading-none tracking-[0.18em] transition-colors duration-300',
            tone === 'light' ? 'text-ivory-100' : 'text-ink-900'
          )}
        >
          Studioz
          <span className={tone === 'light' ? 'text-brand-teal-light' : 'text-brand-teal'}> D</span>
        </span>
      </span>
    )}
  </Link>
);

export default Logo;
